name: Continuous Integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-dev'

jobs:
  linux:
    name: linux-clang
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/pisex/ubuntu20:latest

    env:
      SDKS: '["cs2"]'
      DEPENDENCIES_FOLDER: dependencies
      DEPENDENCIES_ROOT: ${{ github.workspace }}/dependencies

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: metamod-source

      - name: Install system deps
        run: |
          apt update
          apt install -y \
            git clang python3 python3-pip \
            gcc-multilib g++-multilib

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip setuptools wheel

      - name: Install AMBuild
        run: |
          git clone https://github.com/alliedmodders/ambuild
          cd ambuild
          pip3 install .

      - name: Install CS2 SDK (custom fork)
        run: |
          mkdir -p $DEPENDENCIES_FOLDER
          cd $DEPENDENCIES_FOLDER

          HL2SDK_DIR="hl2sdk-cs2"

          if [ ! -d "$HL2SDK_DIR/.git" ]; then
            git clone --recursive \
              --branch SlynxCZ/cs2 \
              --single-branch \
              https://github.com/FUNPLAY-pro-CS2/hl2sdk.git \
              "$HL2SDK_DIR"
          fi

      - name: Build
        working-directory: metamod-source
        run: |
          mkdir build && cd build
          python3 ../configure.py \
            --enable-optimize \
            --sdks=cs2 \
            --hl2sdk-root=$DEPENDENCIES_ROOT
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metamod-cs2-linux
          path: |
            metamod-source/build/package/**
            metamod-source/build/**/*.so
