name: Continuous Integration
on: 
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-dev'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_short: windows
            compiler_cc: msvc-vs2022

          - os: windows-2022
            os_short: windows
            compiler_cc: msvc-vs2019
          - os: ubuntu-22.04
            os_short: linux
            compiler_cc: clang-10
            compiler_cxx: clang++-10
            compiler_install: clang-10
            use_container: true

      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os_short }}-${{ matrix.compiler_cc }}

    container:
      image: ${{ matrix.use_container && 'ghcr.io/pisex/ubuntu20:latest' || '' }}

    env:
      SDKS: '["episode1","tf2","l4d2","csgo","dota"]'
      DEPENDENCIES_FOLDER: dependencies
      DEPENDENCIES_ROOT: ${{ github.workspace }}/dependencies

    steps:
      - name: Install Linux dependencies
        if: matrix.os_short == 'linux'
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3 python3-pip \
            git ca-certificates \
            gcc-multilib g++-multilib \
            libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 \
            linux-libc-dev \
            lib32z1-dev \
            clang-10

      - uses: actions/checkout@v3
        with:
          submodules: true
          path: metamod-source

      - name: Select HL2SDKs
        run: echo 'SDKS=["cs2"]' >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: hl2sdk
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ join(fromJSON(env.SDKS), '') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel

      - name: Install CS2 SDK (custom fork)
        shell: bash
        run: |
          mkdir -p ${{ env.DEPENDENCIES_FOLDER }}
          cd ${{ env.DEPENDENCIES_FOLDER }}
      
          SDK_ROOT="hl2sdk"
          SDK_DIR="$SDK_ROOT/cs2"
      
          mkdir -p "$SDK_ROOT"
      
          if [ ! -d "$SDK_DIR/.git" ]; then
            git clone --recursive \
              --branch SlynxCZ/cs2 \
              --single-branch \
              https://github.com/FUNPLAY-pro-CS2/hl2sdk.git \
              "$SDK_DIR"
          else
            cd "$SDK_DIR"
            git fetch
            git checkout SlynxCZ/cs2
            git pull
            git submodule update --init --recursive
          fi

      - name: Export CS2 SDK env
        if: matrix.os_short == 'linux'
        run: |
          echo "HL2SDKCS2=${{ env.DEPENDENCIES_ROOT }}/hl2sdk/cs2" >> $GITHUB_ENV

      - name: Select clang compiler
        if: matrix.os_short == 'linux'
        run: |
          echo "CC=${{ matrix.compiler_cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler_cxx }}" >> $GITHUB_ENV
          ${{ matrix.compiler_cc }} --version
          ${{ matrix.compiler_cxx }} --version

      - name: Install AMBuild
        run: |
          git clone https://github.com/alliedmodders/ambuild.git ambuild
          cd ambuild
          pip3 install .
          cd ..

      - name: Build
        working-directory: metamod-source
        run: |
          mkdir build
          cd build
          python3 ../configure.py --enable-optimize \
            --sdks=${{ join(fromJSON(env.SDKS)) }}
          ambuild

      - name: Upload build artifacts (Linux)
        if: matrix.os_short == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: metamod-cs2-linux-${{ matrix.compiler_cc }}
          path: |
            metamod-source/build/package/**
            metamod-source/build/addons/**
            metamod-source/build/**/*.so

      - name: Upload build artifacts (Windows)
        if: matrix.os_short == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: metamod-cs2-windows-${{ matrix.compiler_cc }}
          path: |
            metamod-source/build/package/**
            metamod-source/build/**/*.dll
